/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardComponent: typeof import('./src/components/CardComponent.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    RippleButton: typeof import('./src/components/RippleButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleCard: typeof import('./src/components/SimpleCard.vue')['default']
    WifiLoader: typeof import('./src/components/WifiLoader.vue')['default']
  }
}
